spring.application.name=fleet-management

server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5432/fleet_db

#spring.datasource.url=jdbc:postgresql://host.docker.internal:5432/fleet_db

spring.datasource.username=postgres

spring.datasource.password=admin

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update


management.endpoints.web.exposure.include=health,info,metrics,prometheus

management.endpoint.health.show-details=always

management.prometheus.metrics.export.enabled=true

